version: "3.8"
services:
  backend:
    environment:
      NODE_ENV: development
    volumes:
      - ./universal-medusa-app:/app/medusa
      - universal-medusa-app_node_modules:/app/medusa/node_modules
    ports:
      - "9000:9000"
      - "7001:7001"
    
    # network_mode: host
    
  # admin:
  #   ports:
  #     - "7000:7000"

  # storefront:
  #   volumes:
  #     - ./universal-storefront:/app/storefront
  #     - universal-storefront_node_modules:/app/storefront/node_modules
  #   ports:
  #     - "8000:8000"

volumes:
  # universal-storefront_node_modules:
  universal-medusa-app_node_modules:
