ARG NODE_VERSION=18.17.1

FROM node:${NODE_VERSION}-slim as base

# ARG PORT=3000

ENV NODE_ENV=development

# WORKDIR /src
WORKDIR /app



FROM base as build

# COPY --link package.json package-lock.json ./
COPY --link package.json ./

RUN npm install



FROM base

COPY --from=build /app/node_modules /app/node_modules
# COPY . ./app


# CMD ["npm", "run", "dev"]

# CMD ["npm", "--version"]